### PR TITLE
Update .travis.yml to execute apt-get update

### PR DESCRIPTION
**Pull request by DennyLoko**
The apt should be updated before installing any package.

### CODE REVIEW

**Comment by DennyLoko** [comment]
@mccraveiro Nope, I never tried it before. How is it different than manually adding the packages?

**Comment by mccraveiro** [comment]
@DennyLoko I never tried it too. However it seems to be faster as it won't run `apt-get update`

**Comment by mccraveiro** [comment]
Why is this PR still open? Let's ship it

**Comment by mccraveiro** [comment]
Closing due to inactivity

**Pull request closed without merging**
